# Generated by Django 4.2.30 on 2026-07-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        ('items', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='requester_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trade_requests', to='items.item'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='target_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trade_requests', to='items.item'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='traderequest',
            unique_together={('requester_item', 'target_item')},
        ),
    ]
